Repository iamlogand/republic-of-rome-online, pull requests merged in 2023-07, with the labels that each got.

#125 Remove all references to Gunicorn
  backend/Dockerfile
  backend/requirements.txt
Labels: Refactoring

#127 Add "How to contribute" steps to the README
  README.md
Labels: Documentation

#126 Move the sign in form to a dedicated page
  frontend/components/TopBar.tsx
  frontend/components/modals/ModalContainer.tsx
  frontend/components/modals/SignOutModal.tsx
  frontend/pages/games/index.tsx
  frontend/pages/games/new.tsx
  frontend/pages/sign-in.tsx
Labels: Feature

#129 Add confirmation on game deletion
  frontend/pages/games/[id].tsx
Labels: Feature

#122 Created the form for join waitlist
  backend/rorapp/admin/__init__.py
  backend/rorapp/admin/waitlist_entry.py
  backend/rorapp/migrations/0012_waitlistentry.py
  backend/rorapp/models/__init__.py
  backend/rorapp/models/waitlist_entry.py
  backend/rorapp/serializers/__init__.py
  backend/rorapp/serializers/waitlist_entry.py
  backend/rorapp/urls.py
  backend/rorapp/views/__init__.py
  backend/rorapp/views/waitlist_entry.py
  frontend/functions/request.ts
  frontend/pages/index.tsx
Labels: Feature

#130 Add the edit game page
  backend/rorapp/views/game.py
  frontend/components/Breadcrumb.tsx
  frontend/pages/games/[id]/edit.tsx
  frontend/pages/games/[id]/index.tsx
  frontend/pages/games/new.tsx
Labels: Feature

#133 Enable hosts to kick game participants
  backend/rorapp/views/game_participant.py
  frontend/pages/games/[id]/index.tsx
  roronline.code-workspace
Labels: Feature

#137 Add throttling to the waitlist API endpoint
  backend/rorapp/views/waitlist_entry.py
  frontend/pages/index.tsx
Labels: Feature

#134 User joining waitlist a second time should pretend first time join
  backend/rorapp/migrations/0013_alter_waitlistentry_options.py
  backend/rorapp/views/waitlist_entry.py
Labels: Feature

#144 Changed styling of join waitlist to full width on mobile and fixed size for bigger screens
  frontend/pages/index.tsx
Labels: Cosmetic

#150 Add a unit test for the user viewset (API)
  .github/workflows/ci_backend.yml
  backend/rorapp/tests.py
  backend/rorapp/tests/__init__.py
  backend/rorapp/tests/user_viewset.py
  backend/rorsite/settings.py
Labels: Testing
