Repository iamlogand/republic-of-rome-online, pull requests merged in 2023-05, with the labels that each got.

#89 Fix enter key not submitting form issue
  frontend/components/modals/SignInModal.tsx
Labels: Bug

#90 API support for game deletion
  backend/rorapp/serializers/__init__.py
  backend/rorapp/serializers/game.py
  backend/rorapp/views/game.py
Labels: Feature

#91 Enable game deletion in the UI
  frontend/components/Button.module.css
  frontend/components/Button.tsx
  frontend/components/LinkedTableRow.module.css
  frontend/components/TopBar.tsx
  frontend/pages/games/[id].tsx
  frontend/styles/color.css
Labels: Feature

#93 Add a VS Code workspace
  backend/.vscode/settings.json
  roronline.code-workspace
Labels: Tooling

#97 Migrate to Material UI
  frontend/README.md
  frontend/components/Breadcrumb.module.css
  frontend/components/Breadcrumb.tsx
  frontend/components/Button.module.css
  frontend/components/Button.tsx
  frontend/components/ExternalLink.tsx
  frontend/components/Footer.module.css
  frontend/components/KeyValueStack.tsx
  frontend/components/Link.module.css
  frontend/components/Link.tsx
  frontend/components/LinkedTableRow.module.css
  frontend/components/LinkedTableRow.tsx
  frontend/components/TopBar.module.css
  frontend/components/TopBar.tsx
  frontend/components/modals/ModalContainer.module.css
  frontend/components/modals/ModalTitle.module.css
  frontend/components/modals/ModalTitle.tsx
  frontend/components/modals/SignInModal.tsx
  frontend/components/modals/SignOutModal.tsx
  frontend/components/senators/SenatorInspector.module.css
  frontend/components/senators/SenatorInspector.tsx
  frontend/components/senators/SenatorName.tsx
  frontend/components/senators/SenatorPortrait.module.css
  frontend/contexts/RootContext.tsx
  frontend/fonts/TrajanProRegular.ttf
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/pages/account.tsx
  frontend/pages/games/[id].tsx
  frontend/pages/games/index.module.css
  frontend/pages/games/index.tsx
  frontend/pages/games/new.tsx
  frontend/pages/index.tsx
  frontend/styles/color.css
  frontend/styles/dataGrid.css
  frontend/styles/form.css
  frontend/styles/heading.css
  frontend/styles/layout.css
  frontend/styles/master.css
  frontend/styles/table.css
  frontend/themes/frameTheme.ts
  frontend/themes/mainTheme.ts
  frontend/themes/rootTheme.ts
Labels: Cosmetic, Feature

#98 Fix MUI X DataGrid popover and menu font family
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/styles/master.css
  frontend/themes/mainTheme.ts
  frontend/themes/rootTheme.ts
Labels: Cosmetic, Bug

#99 Fix MUI X DataGrid font color
  frontend/themes/rootTheme.ts
Labels: Cosmetic, Bug

#101 Allow users to join a game
  backend/rorapp/models/__init__.py
  backend/rorapp/models/game_participant.py
  backend/rorapp/serializers/__init__.py
  backend/rorapp/serializers/game_participant.py
  backend/rorapp/urls.py
  backend/rorapp/views/__init__.py
  backend/rorapp/views/game.py
  backend/rorapp/views/game_participant.py
  frontend/components/KeyValueList.tsx
  frontend/components/KeyValueStack.tsx
  frontend/pages/account.tsx
  frontend/pages/games/[id].tsx
  frontend/pages/games/index.tsx
  frontend/pages/games/new.tsx
  frontend/pages/index.tsx
Labels: Feature

#105 Allow players to leave a game
  backend/rorapp/serializers/game.py
  backend/rorapp/views/game_participant.py
  frontend/classes/Game.ts
  frontend/pages/games/[id].tsx
Labels: Feature

#108 Stop host from leaving their own game
  backend/rorapp/views/game_participant.py
  frontend/pages/games/[id].tsx
Labels: Feature

#111 Add a CI workflow for the backend
  .github/workflows/ci_backend.yml
Labels: Tooling

#112 Simplify CI backend RDS setup and related Django settings
  .github/workflows/ci_backend.yml
  backend/rorsite/settings.py
Labels: Tooling

#115 After game creation, redirect to game page
  backend/.gitignore
  backend/rorapp/serializers/game.py
  frontend/pages/games/new.tsx
Labels: Feature

#117 Can't create a new game
  backend/rorapp/serializers/game.py
Labels: Bug
